import React from 'react';
import Navbar from 'src/components/layout/navbar';
import { Poppins } from 'next/font/google';

import '../styles/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${poppins.variable}`}>
      <body className='min-h-screen bg-[#F8FAFC]'>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
